---
- name: update apt
  apt: update_cache=yes

- name: install pgmagick deps
  apt: pkg={{item}}
  with_items:
  - python-pgmagick
  - python-pip
  - python-dev
  - git-core
  - libjpeg-dev
  - libtiff-dev
  - libpng-dev
  - libjasper-dev
  - libwebp-dev

- name: install pycurl deps
  apt: pkg={{item}}
  with_items:
  - libcurl4-openssl-dev
  - libssl-dev
  - python-dev

- name: install pgmagick
  pip: >
    name={{item}}
  with_items:
    - pycurl
    - numpy
    - thumbor

- name: copy thumbor conf default
  template: >
    src=thumbor.conf.j2
    dest={{ thumbor_config_file }}
    owner=root
    group=root
    mode=0755

- name: copy thumbor key
  template: >
    src=thumbor.key.j2
    dest={{ thumbor_key_file }}
    owner=root
    group=root
    mode=0755

- name: working dir
  file: >
    path={{thumbor_working_directory}}
    owner=root
    group=root
    mode=0644
    state=directory

- name: copy thumbor systemd script
  template: >
    src=thumbor.service.j2
    dest=/lib/systemd/system/thumbor.service
    owner=root
    group=root
    mode=644

- service: >
    name=thumbor
    state=started
    enabled=yes
