---
- name: update apt
  apt: update_cache=yes

- name: install pgmagick deps
  apt: pkg={{item}}
  with_items:
  - python-pgmagick
  - python-pip
  - python-dev
  - git-core
  - libjpeg-dev
  - libtiff-dev
  - libpng-dev
  - libjasper-dev
  - libwebp-dev

- name: install pycurl deps
  apt: pkg={{item}}
  with_items:
  - libcurl4-openssl-dev
  - libssl-dev
  - python-dev

# NB! newest thumbor has breaking chenges!
# TODO: upgrade to newest thumbor
- name: install thumbor
  pip: name={{item.pkg}} version={{item.version}}
  with_items:
    - { pkg: thumbor, version: 5.2.1 }
    - { pkg: remotecv, version: 1.0.3 }
    - { pkg: redis, version: 2.4.12 }

- name: copy thumbor conf default
  template: >
    src=thumbor.conf.j2
    dest={{ thumbor_config_file }}
    owner=root
    group=root
    mode=0755

- name: copy thumbor key
  template: >
    src=thumbor.key.j2
    dest={{ thumbor_key_file }}
    owner=root
    group=root
    mode=0755

- name: working dir
  file: >
    path={{thumbor_working_directory}}
    owner=root
    group=root
    mode=0644
    state=directory

- name: copy thumbor systemd script
  template: >
    src=thumbor.service.j2
    dest=/lib/systemd/system/thumbor.service
    owner=root
    group=root
    mode=644

- service: >
    name=thumbor
    state=started
    enabled=yes
