# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANT_VM_PROVIDER = "virtualbox"
ANSIBLE_RAW_SSH_ARGS = []
VAGRANT_DOTFILE_PATH = ".vagrant"

Vagrant.configure(2) do |config|
  config.vm.define "thumborbasetest" do |machine|
    machine.vm.box = "debian/jessie64"
    machine.vm.hostname = "thumborbasetest"
    machine.vm.network :private_network, ip: "192.168.100.10"
    machine.vm.provision :ansible do |ansible|
      ansible.playbook = "test.yml"
      ansible.inventory_path = "./inventory"
      ansible.limit = 'all'
      ansible.verbose = 'vvvv'
      ansible.sudo = true
    end
  end
end
